[package]
name = "krun-nitro-eif-ctl"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/tylerfanelli/krun-nitro-eif-ctl"
authors = ["Tyler Fanelli <tfanelli@redhat.com>"]
description = "krun-nitro EIF configuration tool"

[dependencies]
